// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbtwpmdaposlkxsxpgnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZidHdwbWRhcG9zbGt4c3hwZ25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDkyODUsImV4cCI6MjA3MzQ4NTI4NX0.w73xYI0253pKHu_EI_VJQjXWSog4SBxbb1eSdZffgpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});